/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sams_phase4;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;
/**
 *
 * @author apatel3145
 */
public class REGISTRATION_PAGE extends javax.swing.JFrame {

    /**
     * Creates new form REGISTRATION_PAGE
     */
    public REGISTRATION_PAGE() {
        JPanel backgroundPanel = new JPanel() {
            Image background = new ImageIcon("C:/Users/apatel3145/Downloads/download.jpg").getImage();

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(background, 0, 0, getWidth(), getHeight(), this);
            }
        };
        backgroundPanel.setLayout(new BorderLayout()); // Set layout if you want to add components

        
        setContentPane(backgroundPanel);

        setLocationRelativeTo(null);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
setSize(screenSize.width, screenSize.height);
setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        brp1 = new javax.swing.JButton();
        brp2 = new javax.swing.JButton();
        brp3 = new javax.swing.JButton();
        rp4 = new javax.swing.JButton();
        rp5 = new javax.swing.JButton();
        rp6 = new javax.swing.JButton();
        rp7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        brp1.setText("MANAGE LOCATION");
        brp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brp1ActionPerformed(evt);
            }
        });

        brp2.setText("MANAGE AIRLINE");
        brp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brp2ActionPerformed(evt);
            }
        });

        brp3.setText("MANAGE AIRPLANE");
        brp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brp3ActionPerformed(evt);
            }
        });

        rp4.setText("MANAGE LEG");
        rp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp4ActionPerformed(evt);
            }
        });

        rp5.setText("MANAGE ROUTE");
        rp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp5ActionPerformed(evt);
            }
        });

        rp6.setText("MANAGE FLIGHT");
        rp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp6ActionPerformed(evt);
            }
        });

        rp7.setText("MANAGE AIRPORT");
        rp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp7ActionPerformed(evt);
            }
        });

        jButton1.setText("RETURN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MANAGE PERSON");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(brp1)
                        .addComponent(brp2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brp3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(rp4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(368, 368, 368)
                            .addComponent(jButton1))
                        .addComponent(rp5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rp6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rp7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(brp1)
                    .addGap(28, 28, 28)
                    .addComponent(brp2)
                    .addGap(29, 29, 29)
                    .addComponent(brp3)
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rp4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jButton1)))
                    .addGap(20, 20, 20)
                    .addComponent(rp5)
                    .addGap(34, 34, 34)
                    .addComponent(rp6)
                    .addGap(33, 33, 33)
                    .addComponent(rp7)
                    .addGap(26, 26, 26)
                    .addComponent(jButton2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brp1ActionPerformed
REGISTRATION_LOCATION rl = new REGISTRATION_LOCATION();
                
                rl.setVisible(true);

                // Close the current form
                dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_brp1ActionPerformed

    private void brp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brp2ActionPerformed
   REGISTRATION_AIRLINE ra = new REGISTRATION_AIRLINE();

        ra.setVisible(true);

        // Close the current form
        dispose();
    }//GEN-LAST:event_brp2ActionPerformed

    private void brp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brp3ActionPerformed
REGISTRATION_AIRPLANE ra = new REGISTRATION_AIRPLANE();

        ra.setVisible(true);

        // Close the current form
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_brp3ActionPerformed

    private void rp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp4ActionPerformed
REGISTRATION_LEG rl = new REGISTRATION_LEG();

        rl.setVisible(true);

        // Close the current form
        dispose();        // TODO add your handling code here:
         
    }//GEN-LAST:event_rp4ActionPerformed

    private void rp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp5ActionPerformed
REGISTRATION_ROUTE rr = new REGISTRATION_ROUTE();

        rr.setVisible(true);
        dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_rp5ActionPerformed

    private void rp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp6ActionPerformed
  REGISTRATION_FLIGHT ra = new REGISTRATION_FLIGHT();

        ra.setVisible(true);

        // Close the current form
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_rp6ActionPerformed

    private void rp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp7ActionPerformed
REGISTRATION_AIRPORT ra = new REGISTRATION_AIRPORT();

        ra.setVisible(true);

        // Close the current form
        dispose();         // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_rp7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
HOME_PAGE rr = new HOME_PAGE();

        rr.setVisible(true);
        dispose();          // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
REGISTRATION_PERSON rr = new REGISTRATION_PERSON();

        rr.setVisible(true);
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brp1;
    private javax.swing.JButton brp2;
    private javax.swing.JButton brp3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rp4;
    private javax.swing.JButton rp5;
    private javax.swing.JButton rp6;
    private javax.swing.JButton rp7;
    // End of variables declaration//GEN-END:variables
}